### ISSUE TITLE
For: Issue for "AttributeError: 'SQDDPG' object has no attribute 'agent_importance_vec'"

### ISSUE THREAD

**Issue by yqlwqj** [Future-Power-Networks/MAPDN#20]
Hi, I am try reproducing results and have following issue in "sqddpg_33_0_l1.out" while doing "source train_case33.sh 0 l1 reproduction" 
     Traceback (most recent call last):
  File "train.py", line 115, in <module>
    train.run(stat, i)
  File "/home/ben/ben/MAPDN/utilities/trainer.py", line 111, in run
    self.behaviour_net.train_process(stat, self)
  File "/home/ben/ben/MAPDN/models/model.py", line 213, in train_process
    value = self.value(state_, action_pol)
  File "/home/ben/ben/MAPDN/models/sqddpg.py", line 108, in value
    return self.marginal_contribution(obs, act)
  File "/home/ben/ben/MAPDN/models/sqddpg.py", line 66, in marginal_contribution
    subcoalition_map, grand_coalitions, individual_map = self.sample_grandcoalitions(batch_size) # shape = (b, n_s, n, n)
  File "/home/ben/ben/MAPDN/models/sqddpg.py", line 38, in sample_grandcoalitions
    agent_importance_vec = self.agent_importance_vec.unsqueeze(0).expand(batch_size*self.sample_size, self.n_)
  File "/home/ben/anaconda3/envs/mapdn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1266, in __getattr__
    type(self).__name__, name))
AttributeError: 'SQDDPG' object has no attribute 'agent_importance_vec'

May you help for this?

thanks

**Comment by hsvgbkhgbv** [comment]
Hi,

I've fixed the bug. Plesae try it again.

Best,
Jianhong
