### ISSUE TITLE
MPE environment

### ISSUE THREAD

**Issue by mxy123580** [Future-Power-Networks/MAPDN#38]
Whether to support MPE environment？

**Comment by hsvgbkhgbv** [comment]
Hi,

Thank you for your interest. For now, we do no support MPE, but if possible we may make a wrapper to support that soon.

**Comment by lmd123123** [comment]
> Whether to support MPE environment？

When I run train.py, I get an error when reading model.p in case322_3min_final folder. What version of pandas and pandapower are you using? Looking forward to your reply!
This error did not occur when running 33-node and 141 systems.

The code gives an error:
C:\Users\LMD\PycharmProjects\MAPDN\MAPDN-main\train.py:70: SyntaxWarning: "is" with a literal. Did you mean "=="?
if argv.save_path[-1] is "/":
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
File "C:\Users\LMD.conda\envs\MAPDN\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
return self._engine.get_loc(casted_key)
File "pandas_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
File "pandas_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
File "pandas_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\LMD.conda\envs\MAPDN\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
raise KeyError(key) from err
KeyError: 'type'

Process finished with exit code 1
